# Auto-generated by IDE. Changes by user will be lost!
BASEDIR =  $$quote($$_PRO_FILE_PWD_)

device {
    CONFIG(debug, debug|release) {
        SOURCES +=  $$quote($$BASEDIR/src/Models/Msisdn.cpp) \
                 $$quote($$BASEDIR/src/Models/SimBalance.cpp) \
                 $$quote($$BASEDIR/src/Models/TopupHistory.cpp) \
                 $$quote($$BASEDIR/src/Models/Usage.cpp) \
                 $$quote($$BASEDIR/src/Models/VikingPoints.cpp) \
                 $$quote($$BASEDIR/src/Services/LoginService.cpp) \
                 $$quote($$BASEDIR/src/Services/VikingService.cpp) \
                 $$quote($$BASEDIR/src/ViewModels/LoginViewModel.cpp) \
                 $$quote($$BASEDIR/src/ViewModels/MainViewModel.cpp) \
                 $$quote($$BASEDIR/src/ViewModels/MsisdnViewModel.cpp) \
                 $$quote($$BASEDIR/src/ViewModels/PointsViewModel.cpp) \
                 $$quote($$BASEDIR/src/ViewModels/SimBalanceViewModel.cpp) \
                 $$quote($$BASEDIR/src/ViewModels/TopupHistoryListViewModel.cpp) \
                 $$quote($$BASEDIR/src/ViewModels/TopupHistoryViewModel.cpp) \
                 $$quote($$BASEDIR/src/ViewModels/UsageListViewModel.cpp) \
                 $$quote($$BASEDIR/src/ViewModels/UsageViewModel.cpp) \
                 $$quote($$BASEDIR/src/applicationui.cpp) \
                 $$quote($$BASEDIR/src/main.cpp)

        HEADERS +=  $$quote($$BASEDIR/src/Models/Msisdn.hpp) \
                 $$quote($$BASEDIR/src/Models/SimBalance.hpp) \
                 $$quote($$BASEDIR/src/Models/TopupHistory.hpp) \
                 $$quote($$BASEDIR/src/Models/Usage.hpp) \
                 $$quote($$BASEDIR/src/Models/UsageType.hpp) \
                 $$quote($$BASEDIR/src/Models/VikingPoints.hpp) \
                 $$quote($$BASEDIR/src/Services/LoginService.hpp) \
                 $$quote($$BASEDIR/src/Services/VikingService.hpp) \
                 $$quote($$BASEDIR/src/ViewModels/LoginViewModel.hpp) \
                 $$quote($$BASEDIR/src/ViewModels/MainViewModel.hpp) \
                 $$quote($$BASEDIR/src/ViewModels/MsisdnViewModel.hpp) \
                 $$quote($$BASEDIR/src/ViewModels/PointsViewModel.hpp) \
                 $$quote($$BASEDIR/src/ViewModels/SimBalanceViewModel.hpp) \
                 $$quote($$BASEDIR/src/ViewModels/TopupHistoryListViewModel.hpp) \
                 $$quote($$BASEDIR/src/ViewModels/TopupHistoryViewModel.hpp) \
                 $$quote($$BASEDIR/src/ViewModels/UsageListViewModel.hpp) \
                 $$quote($$BASEDIR/src/ViewModels/UsageViewModel.hpp) \
                 $$quote($$BASEDIR/src/applicationui.hpp)

    }

    CONFIG(release, debug|release) {
        SOURCES +=  $$quote($$BASEDIR/src/Models/Msisdn.cpp) \
                 $$quote($$BASEDIR/src/Models/SimBalance.cpp) \
                 $$quote($$BASEDIR/src/Models/TopupHistory.cpp) \
                 $$quote($$BASEDIR/src/Models/Usage.cpp) \
                 $$quote($$BASEDIR/src/Models/VikingPoints.cpp) \
                 $$quote($$BASEDIR/src/Services/LoginService.cpp) \
                 $$quote($$BASEDIR/src/Services/VikingService.cpp) \
                 $$quote($$BASEDIR/src/ViewModels/LoginViewModel.cpp) \
                 $$quote($$BASEDIR/src/ViewModels/MainViewModel.cpp) \
                 $$quote($$BASEDIR/src/ViewModels/MsisdnViewModel.cpp) \
                 $$quote($$BASEDIR/src/ViewModels/PointsViewModel.cpp) \
                 $$quote($$BASEDIR/src/ViewModels/SimBalanceViewModel.cpp) \
                 $$quote($$BASEDIR/src/ViewModels/TopupHistoryListViewModel.cpp) \
                 $$quote($$BASEDIR/src/ViewModels/TopupHistoryViewModel.cpp) \
                 $$quote($$BASEDIR/src/ViewModels/UsageListViewModel.cpp) \
                 $$quote($$BASEDIR/src/ViewModels/UsageViewModel.cpp) \
                 $$quote($$BASEDIR/src/applicationui.cpp) \
                 $$quote($$BASEDIR/src/main.cpp)

        HEADERS +=  $$quote($$BASEDIR/src/Models/Msisdn.hpp) \
                 $$quote($$BASEDIR/src/Models/SimBalance.hpp) \
                 $$quote($$BASEDIR/src/Models/TopupHistory.hpp) \
                 $$quote($$BASEDIR/src/Models/Usage.hpp) \
                 $$quote($$BASEDIR/src/Models/UsageType.hpp) \
                 $$quote($$BASEDIR/src/Models/VikingPoints.hpp) \
                 $$quote($$BASEDIR/src/Services/LoginService.hpp) \
                 $$quote($$BASEDIR/src/Services/VikingService.hpp) \
                 $$quote($$BASEDIR/src/ViewModels/LoginViewModel.hpp) \
                 $$quote($$BASEDIR/src/ViewModels/MainViewModel.hpp) \
                 $$quote($$BASEDIR/src/ViewModels/MsisdnViewModel.hpp) \
                 $$quote($$BASEDIR/src/ViewModels/PointsViewModel.hpp) \
                 $$quote($$BASEDIR/src/ViewModels/SimBalanceViewModel.hpp) \
                 $$quote($$BASEDIR/src/ViewModels/TopupHistoryListViewModel.hpp) \
                 $$quote($$BASEDIR/src/ViewModels/TopupHistoryViewModel.hpp) \
                 $$quote($$BASEDIR/src/ViewModels/UsageListViewModel.hpp) \
                 $$quote($$BASEDIR/src/ViewModels/UsageViewModel.hpp) \
                 $$quote($$BASEDIR/src/applicationui.hpp)

    }

}

simulator {
    CONFIG(debug, debug|release) {
        SOURCES +=  $$quote($$BASEDIR/src/Models/Msisdn.cpp) \
                 $$quote($$BASEDIR/src/Models/SimBalance.cpp) \
                 $$quote($$BASEDIR/src/Models/TopupHistory.cpp) \
                 $$quote($$BASEDIR/src/Models/Usage.cpp) \
                 $$quote($$BASEDIR/src/Models/VikingPoints.cpp) \
                 $$quote($$BASEDIR/src/Services/LoginService.cpp) \
                 $$quote($$BASEDIR/src/Services/VikingService.cpp) \
                 $$quote($$BASEDIR/src/ViewModels/LoginViewModel.cpp) \
                 $$quote($$BASEDIR/src/ViewModels/MainViewModel.cpp) \
                 $$quote($$BASEDIR/src/ViewModels/MsisdnViewModel.cpp) \
                 $$quote($$BASEDIR/src/ViewModels/PointsViewModel.cpp) \
                 $$quote($$BASEDIR/src/ViewModels/SimBalanceViewModel.cpp) \
                 $$quote($$BASEDIR/src/ViewModels/TopupHistoryListViewModel.cpp) \
                 $$quote($$BASEDIR/src/ViewModels/TopupHistoryViewModel.cpp) \
                 $$quote($$BASEDIR/src/ViewModels/UsageListViewModel.cpp) \
                 $$quote($$BASEDIR/src/ViewModels/UsageViewModel.cpp) \
                 $$quote($$BASEDIR/src/applicationui.cpp) \
                 $$quote($$BASEDIR/src/main.cpp)

        HEADERS +=  $$quote($$BASEDIR/src/Models/Msisdn.hpp) \
                 $$quote($$BASEDIR/src/Models/SimBalance.hpp) \
                 $$quote($$BASEDIR/src/Models/TopupHistory.hpp) \
                 $$quote($$BASEDIR/src/Models/Usage.hpp) \
                 $$quote($$BASEDIR/src/Models/UsageType.hpp) \
                 $$quote($$BASEDIR/src/Models/VikingPoints.hpp) \
                 $$quote($$BASEDIR/src/Services/LoginService.hpp) \
                 $$quote($$BASEDIR/src/Services/VikingService.hpp) \
                 $$quote($$BASEDIR/src/ViewModels/LoginViewModel.hpp) \
                 $$quote($$BASEDIR/src/ViewModels/MainViewModel.hpp) \
                 $$quote($$BASEDIR/src/ViewModels/MsisdnViewModel.hpp) \
                 $$quote($$BASEDIR/src/ViewModels/PointsViewModel.hpp) \
                 $$quote($$BASEDIR/src/ViewModels/SimBalanceViewModel.hpp) \
                 $$quote($$BASEDIR/src/ViewModels/TopupHistoryListViewModel.hpp) \
                 $$quote($$BASEDIR/src/ViewModels/TopupHistoryViewModel.hpp) \
                 $$quote($$BASEDIR/src/ViewModels/UsageListViewModel.hpp) \
                 $$quote($$BASEDIR/src/ViewModels/UsageViewModel.hpp) \
                 $$quote($$BASEDIR/src/applicationui.hpp)

    }

}

INCLUDEPATH +=  $$quote($$BASEDIR/src/Models) \
         $$quote($$BASEDIR/src/ViewModels) \
         $$quote($$BASEDIR/src) \
         $$quote($$BASEDIR/src/Services)

CONFIG += precompile_header

PRECOMPILED_HEADER =  $$quote($$BASEDIR/precompiled.h)

lupdate_inclusion {
    SOURCES +=  $$quote($$BASEDIR/../assets/*.qml)

}

TRANSLATIONS =  $$quote($${TARGET}_fr.ts) \
         $$quote($${TARGET}_nl.ts) \
         $$quote($${TARGET}.ts)

